"""
Pentest report generator.

Collates everything collected in the current session (scan results,
captured creds, cracked keys, MITM activity, portal submissions) into a
self-contained HTML assessment report with findings + mitigations.
"""
import json
import time
from datetime import datetime

from open80211.core import ui
from open80211.core.config import CONFIG

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>open80211 Assessment Report</title>
<style>
 body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 0;
        background: #0e1117; color: #e6edf3; }}
 .wrap {{ max-width: 960px; margin: 0 auto; padding: 32px; }}
 h1 {{ color: #58a6ff; border-bottom: 2px solid #30363d; padding-bottom: 8px; }}
 h2 {{ color: #58a6ff; margin-top: 40px; }}
 table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
 th, td {{ border: 1px solid #30363d; padding: 6px 10px; text-align: left; font-size: 14px; }}
 th {{ background: #161b22; }}
 tr:nth-child(even) {{ background: #11161d; }}
 .badge {{ display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 12px; }}
 .crit {{ background: #f85149; color: #fff; }}
 .high {{ background: #d29922; color: #000; }}
 .med  {{ background: #58a6ff; color: #fff; }}
 .low  {{ background: #3fb950; color: #fff; }}
 .mono {{ font-family: ui-monospace, Consolas, monospace; font-size: 13px;
         word-break: break-all; }}
 .footer {{ margin-top: 60px; color: #8b949e; font-size: 12px; }}
 .sev td:first-child {{ font-weight: bold; }}
</style>
</head>
<body><div class="wrap">
<h1>open80211 Wireless Security Assessment</h1>
<p><b>Report ID:</b> {report_id} &nbsp; <b>Generated:</b> {generated}</p>

<h2>1. Executive Summary</h2>
<p>{summary}</p>

<h2>2. Scope & Environment</h2>
<table>
<tr><th>Interface</th><td class="mono">{interface}</td></tr>
<tr><th>Session directory</th><td class="mono">{session_dir}</td></tr>
<tr><th>Results files</th><td>{files}</td></tr>
</table>

<h2>3. Wireless Reconnaissance</h2>
<table>
<tr><th>BSSID</th><th>SSID</th><th>Channel</th><th>Encryption</th>
<th>Signal</th><th>Clients</th></tr>
{ap_rows}
</table>

<h2>4. Client Devices</h2>
<table><tr><th>MAC</th><th>Probes</th><th>Associated</th></tr>{client_rows}</table>

<h2>5. Harvested Credentials</h2>
<table><tr><th>Protocol</th><th>Data</th><th>Source</th></tr>{cred_rows}</table>

<h2>6. Cracking Results</h2>
<table><tr><th>SSID</th><th>PSK</th></tr>{crack_rows}</table>

<h2>7. MITM Activity</h2>
<table><tr><th>Metric</th><th>Value</th></tr>{mitm_rows}</table>

<h2>8. Portal / Evil AP submissions</h2>
<table><tr><th>Client</th><th>Payload</th><th>Time</th></tr>{portal_rows}</table>

<h2>9. Bluetooth / BLE Findings</h2>
<table><tr><th>Field</th><th>Value</th></tr>{bt_rows}</table>

<h2>10. Cellular / SIM Findings</h2>
<table><tr><th>Field</th><th>Value</th></tr>{cell_rows}</table>

<h2>11. IoT Findings</h2>
<table><tr><th>Field</th><th>Value</th></tr>{iot_rows}</table>

<h2>12. Brute-Force Results</h2>
<table><tr><th>Target</th><th>Protocol</th><th>Credentials</th></tr>{brute_rows}</table>

<h2>13. Engagement Timeline</h2>
<table><tr><th>Time</th><th>Action</th><th>Detail</th></tr>{timeline_rows}</table>

<h2>14. Notes</h2>
<table><tr><th>Time</th><th>Note</th></tr>{note_rows}</table>

<h2>15. Findings & Recommendations</h2>
{findings}

<div class="footer">Generated by open80211 - for authorized assessments only.</div>
</div></body></html>
"""

FINDINGS = [
    ("Open / unencrypted network", "med",
     "No authentication or encryption. Captured without keys.",
     "Enable WPA3/WPA2-Enterprise with 802.1X."),
    ("WEP network in use", "high",
     "WEP is cryptographically broken; crackable in minutes.",
     "Upgrade to WPA3/WPA2-AES (CCMP)."),
    ("WPA2-PSK", "med",
     "PSK networks are vulnerable to offline dictionary attack on captured handshakes/PMKID.",
     "Use WPA3-SAE or a strong (>12 char random) passphrase."),
    ("WPA3-SAE detected", "low",
     "Modern cipher, but SAE downgrade and some implementations remain vulnerable.",
     "Keep firmware current; disable WPA3 transition mode where possible."),
    ("Plaintext credentials observed", "crit",
     "HTTP/FTP/Telnet/POP3 credentials were captured in the clear.",
     "Migrate all auth to TLS; disable legacy protocols."),
    ("LLMNR/NBT-NS/mDNS poisoning possible", "high",
     "Legacy name resolution allows credential capture.",
     "Disable LLMNR/NBT-NS in Group Policy; use DNS with DNSSEC."),
    ("Rogue AP / Evil twin feasible", "high",
     "Client SSID auto-connect allows impersonation attacks.",
     "Use WPA3-EAP + certificates; disable auto-join for unknown networks."),
    ("WPS enabled", "med",
     "WPS PIN reduces PSK to 11,000 possible values.",
     "Disable WPS or enable lockout / per-device PIN."),
    ("Management frame protection (802.11w) not used", "med",
     "Deauth/disconnect attacks succeed against unprotected APs.",
     "Enable PMF (802.11w) and require it on WPA3."),
    ("Bluetooth discoverable / legacy PIN", "med",
     "Classic BT devices with legacy pairing are exposed to PIN brute force, "
     "BlueBorne-type exploits, and KNOB downgrade.",
     "Disable discoverable mode, use secure simple pairing (SSP), patch firmware."),
    ("Cellular / SIM exposure", "med",
     "SIM identity (IMSI/ICCID), SMS and USSD are readable via the modem; "
     "IMSI-catcher (fake cell) attacks capture IMSI and SMS.",
     "Use 5G SA / 3GPP AKA; disable 2G fallback; patch modem firmware."),
    ("IoT device exposure", "high",
     "MQTT brokers, RTSP cameras, UPnP and Modbus devices expose "
     "unauthenticated or weak-credentialed control interfaces.",
     "Disable UPnP, authenticate MQTT, change default creds, segment IoT VLAN."),
    ("Weak / default credentials on services", "crit",
     "Network services accepted default or weak login credentials during "
     "authorized brute-force testing.",
     "Enforce strong password policy, MFA, and lockout thresholds."),
]


def _severity_rows(enabled: list) -> str:
    return "\n".join(
        f"<tr class='sev'><td>{s}</td><td><span class='badge {lvl}'>{lvl}</span> "
        f"{desc}</td><td>{fix}</td></tr>"
        for s, lvl, desc, fix in FINDINGS if s in enabled)


def build_report(scan: list = None, clients: list = None, creds: list = None,
                 cracked: list = None, mitm_stats: dict = None,
                 portal: list = None, bt: list = None, cellular: list = None,
                 iot: list = None, brute: list = None,
                 timeline: list = None, notes: list = None) -> str:
    """Assemble the report and write to the session dir. Returns path."""
    from open80211.core.targets import TARGETS
    scan = scan or []
    clients = clients or []
    creds = creds or []
    cracked = cracked or []
    portal = portal or []
    bt = bt or []
    cellular = cellular or []
    iot = iot or []
    brute = brute or []
    timeline = timeline if timeline is not None else TARGETS.timeline
    notes = notes if notes is not None else TARGETS.notes

    ap_rows = "\n".join(
        f"<tr><td class='mono'>{n['bssid']}</td><td>{n['ssid']}</td>"
        f"<td>{n['channel']}</td><td>{n['enc']}</td><td>{n['signal']}dBm</td>"
        f"<td>{len(n.get('clients_detected', []))}</td></tr>" for n in scan)
    client_rows = "\n".join(
        f"<tr><td class='mono'>{c['mac']}</td><td>{','.join(c.get('probes', []))}</td>"
        f"<td>{c.get('associated_to') or '-'}</td></tr>" for c in clients) or \
        "<tr><td colspan='3'>none</td></tr>"
    cred_rows = "\n".join(
        f"<tr><td>{c.get('protocol', '?')}</td><td class='mono'>{str(c.get('data', ''))[:120]}</td>"
        f"<td>{c.get('src', '-')}</td></tr>" for c in creds) or \
        "<tr><td colspan='3'>none</td></tr>"
    crack_rows = "\n".join(
        f"<tr><td>{s}</td><td class='mono'>{p}</td></tr>" for s, p in cracked) or \
        "<tr><td colspan='2'>none</td></tr>"
    mitm_rows = "\n".join(
        f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in (mitm_stats or {}).items()) or \
        "<tr><td colspan='2'>none</td></tr>"
    portal_rows = "\n".join(
        f"<tr><td class='mono'>{c['client']}</td><td class='mono'>{c['post']}</td>"
        f"<td>{datetime.fromtimestamp(c['time']).strftime('%H:%M:%S')}</td></tr>"
        for c in portal) or "<tr><td colspan='3'>none</td></tr>"
    bt_rows = "\n".join(
        f"<tr><td>{k}</td><td class='mono'>{v}</td></tr>"
        for k, v in (bt[0] if isinstance(bt, list) and bt else {}).items()) or \
        "<tr><td colspan='2'>none</td></tr>"
    cell_rows = "\n".join(
        f"<tr><td>{k}</td><td class='mono'>{v}</td></tr>"
        for k, v in (cellular[0] if isinstance(cellular, list) and cellular else {}).items()) or \
        "<tr><td colspan='2'>none</td></tr>"
    iot_rows = "\n".join(
        f"<tr><td class='mono'>{d.get('ip', '?')}</td>"
        f"<td>{','.join(str(p) for p in d.get('open', []))}</td></tr>"
        for d in iot) if iot else "<tr><td colspan='2'>none</td></tr>"
    brute_rows = "\n".join(
        f"<tr><td class='mono'>{b.get('host', '?')}</td><td>{b.get('protocol', '?')}</td>"
        f"<td class='mono'>{', '.join(f'{u}:{p}' for u, p in b.get('found', []))}</td></tr>"
        for b in brute) or "<tr><td colspan='3'>none</td></tr>"
    timeline_rows = "\n".join(
        f"<tr><td class='mono'>{datetime.fromtimestamp(e['time']).strftime('%H:%M:%S')}</td>"
        f"<td>{e.get('action', '')}</td><td class='mono'>{e.get('detail', '')[:80]}</td></tr>"
        for e in timeline[-40:]) or "<tr><td colspan='3'>none</td></tr>"
    note_rows = "\n".join(
        f"<tr><td class='mono'>{datetime.fromtimestamp(n['time']).strftime('%H:%M:%S')}</td>"
        f"<td>{n.get('text', '')}</td></tr>" for n in notes) or \
        "<tr><td colspan='2'>none</td></tr>"

    # derive findings present
    encs = {n.get("enc", "") for n in scan}
    findings_enabled = set()
    for e in encs:
        if "Open" in e:
            findings_enabled.add("Open / unencrypted network")
        if "WEP" in e:
            findings_enabled.add("WEP network in use")
        if "WPA2" in e or "WPA" in e:
            findings_enabled.add("WPA2-PSK")
        if "WPA3" in e:
            findings_enabled.add("WPA3-SAE detected")
    if creds:
        findings_enabled.add("Plaintext credentials observed")
    if mitm_stats:
        findings_enabled.add("LLMNR/NBT-NS/mDNS poisoning possible")
        findings_enabled.add("Rogue AP / Evil twin feasible")
    if bt and any(isinstance(b, dict) for b in bt):
        findings_enabled.add("Bluetooth discoverable / legacy PIN")
    if cellular:
        findings_enabled.add("Cellular / SIM exposure")
    if iot:
        findings_enabled.add("IoT device exposure")
    if brute and any(b.get("found") for b in brute):
        findings_enabled.add("Weak / default credentials on services")

    summary = f"Identified {len(scan)} access points, {len(clients)} client devices; " \
              f"captured {len(creds)} credential sets" + \
              (f" and recovered {len(cracked)} keys." if cracked else ".") + \
              f" Found {len(findings_enabled)} applicable findings."
    files = ", ".join(f.name for f in sorted(CONFIG.session_dir.iterdir()))

    html = TEMPLATE.format(
        report_id=CONFIG.run_id,
        generated=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        summary=summary,
        interface=CONFIG.interface or "-",
        session_dir=str(CONFIG.session_dir),
        files=files or "none",
        ap_rows=ap_rows,
        client_rows=client_rows,
        cred_rows=cred_rows,
        crack_rows=crack_rows,
        mitm_rows=mitm_rows,
        portal_rows=portal_rows,
        bt_rows=bt_rows,
        cell_rows=cell_rows,
        iot_rows=iot_rows,
        brute_rows=brute_rows,
        timeline_rows=timeline_rows,
        note_rows=note_rows,
        findings=_severity_rows(findings_enabled),
    )
    out = CONFIG.save("open80211-report", html, "html")
    ui.ok(f"Report generated -> {out}")
    return str(out)


def _load_json(name: str):
    p = CONFIG.session_dir / f"{name}.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def build_session_report() -> str:
    """Build a report straight from the shared target registry."""
    from open80211.core.targets import TARGETS
    ui.section("Report Generator", "compiles from engagement registry")
    return build_report(
        scan=TARGETS.aps,
        clients=TARGETS.clients,
        creds=TARGETS.creds,
        cracked=_cracked_pairs(),
        portal=_portal_subs(),
        bt=TARGETS.bluetooth,
        cellular=[TARGETS.cellular] if TARGETS.cellular else [],
        iot=TARGETS.iot,
        brute=_brute_findings(),
    )


def _cracked_pairs() -> list:
    c = _load_json("cracked")
    if c:
        return [(c.get("ssid", "?"), c.get("psk", "?"))]
    return []


def _portal_subs() -> list:
    portal = _load_json("responder_captures") or []
    return portal if isinstance(portal, list) else []


def _brute_findings() -> list:
    out = []
    for f in sorted(CONFIG.session_dir.glob("brute-*.json")):
        try:
            out.append(json.loads(f.read_text()))
        except Exception:
            pass
    return out


def report_menu() -> None:
    """Guided report build from everything already saved this session."""
    ui.section("Report Generator", "compiles session results")
    recon = _load_json("recon_report") or {}
    creds = _load_json("mitm_report") or []
    cracked = []
    c = _load_json("cracked")
    if c:
        cracked = [(c.get("ssid", "?"), c.get("psk", "?"))]
    portal = _load_json("responder_captures") or []
    portal = portal if isinstance(portal, list) else []
    bt = _load_json("bt_pin")
    bt = [bt] if bt else []
    cellular = _load_json("cellular_identity")
    cellular = [cellular] if cellular else []
    iot = _load_json("iot_discovery")
    iot = iot if isinstance(iot, list) else ([iot] if iot else [])

    brute = []
    for f in sorted(CONFIG.session_dir.glob("brute-*.json")):
        try:
            import json
            brute.append(json.loads(f.read_text()))
        except Exception:
            pass

    ui.info("Checking session data...")
    build_report(scan=recon.get("networks", []),
                 clients=recon.get("clients", []),
                 creds=creds,
                 cracked=cracked,
                 portal=portal,
                 bt=bt,
                 cellular=cellular,
                 iot=iot,
                 brute=brute)